[package]
name = "pyngin"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
wgpu = "0.17"
winit = "0.28"
cgmath = "0.18"
pollster = "0.2"
bytemuck = { version = "1.4", features = ["derive"] }

[lib]
crate-type = ["cdylib"]
